# Generated by Django 5.2 on 2025-04-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techapplication',
            name='jdjsmj',
            field=models.CharField(max_length=100, verbose_name='水稻机捕面积'),
        ),
        migrations.AlterField(
            model_name='techapplication',
            name='sdjscd',
            field=models.CharField(max_length=100, verbose_name='水稻收割机械化程度'),
        ),
        migrations.AlterField(
            model_name='techapplication',
            name='sdjxhcd',
            field=models.CharField(max_length=100, verbose_name='水稻机械化程度'),
        ),
    ]
