# Generated by Django 5.2 on 2025-04-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuralOrganization',
            fields=[
                ('jz', models.CharField(max_length=100, verbose_name='镇')),
                ('cmxz', models.CharField(max_length=100, verbose_name='村民小组')),
                ('ncrk', models.CharField(max_length=100, verbose_name='农村人口')),
                ('create_time', models.CharField(max_length=100, verbose_name='写入时间')),
                ('cmwyh', models.CharField(max_length=100, verbose_name='村民委员会')),
                ('dsjzx_taskid', models.CharField(max_length=100, verbose_name='批次号')),
                ('ncjzrk', models.CharField(max_length=100, verbose_name='其中农村居民口')),
                ('jhpt_delete', models.CharField(max_length=100, verbose_name='逻辑删除')),
                ('ncjzhs', models.CharField(max_length=100, verbose_name='其中农村居民户数')),
                ('jhpt_update_time', models.CharField(max_length=100, verbose_name='修改时间')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='自增主键')),
            ],
            options={
                'verbose_name': '农村基层数据',
                'verbose_name_plural': '农村基层数据',
                'db_table': 'rural_organization',
            },
        ),
    ]
