# Generated by Django 5.2 on 2025-04-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_value', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalvalue',
            name='nlmyfwy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='农林牧渔服务业'),
        ),
    ]
