# Generated by Django 5.2 on 2025-04-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_value', '0002_alter_totalvalue_nlmyfwy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalvalue',
            name='jhpt_delete',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='逻辑删除'),
        ),
    ]
