"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s0i47@q%&-u0!yeom8f&#xm5+dx(zp^%mvu&ogm)+3@kb^2e(b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'corsheaders',
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',

        # 自定义的应用
    'rural_organization',
    'tech_application',
    'product_value',
    'total_value',
    'health_organization',
    'main_index',
    'total_agriculture',
    'chat',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'database_test',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 开发环境推荐：允许所有跨域
CORS_ALLOW_ALL_ORIGINS = True

# 生产环境建议指定白名单
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:8080",
#     "http://127.0.0.1:8080",
# ]

# SimpleUI 设置
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['健康组织', '主要指标', '产品价值', '农村组织', '技术应用', '农业总量', '总价值', '认证和授权'],
    'dynamic': True,
    'menus': [
        {
            'name': '健康组织',
            'icon': 'fas fa-hospital',
            'models': [
                {
                    'name': '健康组织管理',
                    'url': 'health_organization/healthorganization/'
                }
            ]
        },
        {
            'name': '主要指标',
            'icon': 'fas fa-chart-line',
            'models': [
                {
                    'name': '主要指标管理',
                    'url': 'main_index/mainindex/'
                }
            ]
        },
        {
            'name': '产品价值',
            'icon': 'fas fa-dollar-sign',
            'models': [
                {
                    'name': '产品价值管理',
                    'url': 'product_value/productvalue/'
                }
            ]
        },
        {
            'name': '农村组织',
            'icon': 'fas fa-users',
            'models': [
                {
                    'name': '农村组织管理',
                    'url': 'rural_organization/ruralorganization/'
                }
            ]
        },
        {
            'name': '技术应用',
            'icon': 'fas fa-cogs',
            'models': [
                {
                    'name': '技术应用管理',
                    'url': 'tech_application/techapplication/'
                }
            ]
        },
        {
            'name': '农业总量',
            'icon': 'fas fa-seedling',
            'models': [
                {
                    'name': '农业总量管理',
                    'url': 'total_agriculture/totalagriculture/'
                }
            ]
        },
        {
            'name': '总价值',
            'icon': 'fas fa-money-bill-wave',
            'models': [
                {
                    'name': '总价值管理',
                    'url': 'total_value/totalvalue/'
                }
            ]
        },
        {
            'app': 'auth',
            'name': '认证和授权',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '用户',
                    'icon': 'fas fa-user',
                    'url': 'auth/user/'
                },
                {
                    'name': '用户组',
                    'icon': 'fas fa-users',
                    'url': 'auth/group/'
                }
            ]
        }
    ],
    # 设置网站标题
    'site_title': '青浦农业后台管理平台',
    # 设置网站图标
    'site_icon': 'fas fa-leaf',
    # 设置登录页面标题
    'login_title': '青浦农业后台管理平台',
    # 设置登录页面Logo
    'login_logo': None,
    # 自定义按钮
    'custom_button': True,
    # 是否显示首页最近操作
    'show_recent_actions': True
}

# 添加以下配置来修改管理界面标题
SIMPLEUI_NAME = '青浦农业后台管理平台'

# 修改管理界面的 Logo
SIMPLEUI_LOGO = '/static/images/logo.png'  # 更新为您的本地 Logo 路径

# 添加静态文件目录配置
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
