# Generated by Django 5.2 on 2025-04-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthOrganization',
            fields=[
                ('xcyss', models.CharField(max_length=100, verbose_name='乡村医生数')),
                ('zhen', models.CharField(max_length=100, verbose_name='镇')),
                ('dsjzx_taskid', models.CharField(max_length=100, verbose_name='批次号')),
                ('jhpt_update_time', models.CharField(max_length=100, verbose_name='时间戳')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='主键')),
                ('xzcs', models.CharField(max_length=100, verbose_name='行政村数')),
                ('jhpt_delete', models.CharField(max_length=100, verbose_name='删除标识')),
            ],
            options={
                'verbose_name': '农村卫生组织',
                'verbose_name_plural': '农村卫生组织',
                'db_table': 'health_organization',
            },
        ),
    ]
